---
kind: TestWorkflow
apiVersion: testworkflows.testkube.io/v1
metadata:
  name: chainsaw-test
  labels:
    app: backend
    testkube.io/name: Chainsaw
    testkube.io/type: infra
spec:
  config:
    namespace:
      type: string
      default: my-app
  content:
    git:
      uri: https://github.com/caiodonascimento/testing-wars.git
      revision: main
      paths:
      - assets/chainsaw
  container:
    image: ghcr.io/kyverno/chainsaw:latest
  pod:
    serviceAccountName: chainsaw-service-account
  steps:
  - name: Run test
    shell: |
      chainsaw test --report-format XML --report-path /data/repo --report-name junit /data/repo/assets/chainsaw --namespace {{ config.namespace }}
    artifacts:
      paths:
        - /data/repo/junit.xml
status: {}
